#! /bin/bash

read -p 'Press enter to launch Gazebo...'
#gnome-terminal --geometry 132x24 -x roslaunch slam_project my_world.launch
gnome-terminal --geometry 132x24 -x roslaunch slam_project  kitchen.launch

read -p 'Press enter to launch Teleop...'
gnome-terminal --geometry 50x24 -x roslaunch slam_project teleop.launch 2>/dev/null

read -p 'Press enter to launch Rtab mapping...'
gnome-terminal --geometry 132x24 -x roslaunch slam_project mapping.launch simulation:=true 2>/dev/null

read -p 'Press enter to launch Rviz...'
gnome-terminal -x roslaunch slam_project rviz.launch 2>/dev/null
echo "Start mapping..."
echo ""

read -p 'Press enter to launch rtabmap-databaseViewer...'
gnome-terminal -x rtabmap-databaseViewer ~/.ros/rtabmap.db

read -p 'Enter the name to save the rtabmap.db (d to delete) ' FILENAME
if [ “$FILENAME” = “d” ]
then
	rm -f ~/.ros/rtabmap.db
	echo "Map deleted" 
else 
	mv ~/.ros/rtabmap.db $FILENAME
	echo "Map moved to ./$FILENAME"
fi

echo "Finished!"
echo ""
